### PR TITLE
Mods to aid compiling

### PR DESCRIPTION
**Pull request by DNNMonster**
Mods to aid compiling per docs.  Added post build to migrate .pdb & .dll for debugging.  I think everything was 2 directories off.  This might help devs following the dev docs.

### CODE REVIEW

**Comment by leedavi** [comment]
Is this working with the new folder structure?

**Comment by DNNMonster** [comment]
I am not aware of a new directory structure.  I followed the instructions on the home page of the repo.  If you follow those instructions I think you end up unable to compile.

**Comment by leedavi** [comment]
Whoops, sorry my fault.  I forgot to update that.  I've done it now.

See if that makes sense.  And let me know if this change still applies.

**Comment by DNNMonster** [comment]
I am not seeing any changes to the instructions so maybe we're not looking at the same instructions?  Install NBrightTemplateSystem install package , this will create a /DesktopModules/NBright/NBrightData folder. Clone this repository into the /DesktopModules/NBright/NBrightData folder.  What was the change?

**Comment by leedavi** [comment]
Yes, I've simply removed the "project" folder where the source was originally.  It was not stadard to link to a clone that does not have the module operating path.

**Comment by DNNMonster** [comment]
OK.  I'll close this until I get a chance to set up a new dev environment.  I may have posted this based upon experiences coming from before that change. I'll re-open if I find an issue.

**Pull request closed without merging**
