### PR TITLE
Mods to support encrypted @TextBox.

### PR DESCRIPTION
**Pull request by DNNMonster**
I believe this will introduce non breaking change support for encrypted text box tokens for plugins & other razor templates.  User generated crypto keys rather than a Portal GUID would make sense but this provides a possible approach to start from.

### CODE REVIEW

**Comment by leedavi** [comment]
Hi,

When overloading a method adding a parameter will break compatiblity, even though logically it will not.  (Not 100% sure on Razor tokens, but I guess it's the same.)

So this change will cause a break.  

-        public IEncodedString TextBox(NBrightInfo info, String xpath, String attributes = "", String defaultValue = "")
+        public IEncodedString TextBox(NBrightInfo info, String xpath, String attributes = "", String defaultValue = "", bool encrypted = false)
         {

You need to create extra methods without the default params for all method params..

**Comment by DNNMonster** [comment]
Hmmm..  Not in our regression testing. If that param is new and
extends the signature with a default I do not believe it will introduce any problems.
Currently using this PR in our build without any issues.  If a user
would like to use the implementation it would require they include all
the params however I am not seeing how it would cause a break in any
previous usage of the token..??  All previous versions in any razor file
would simply be defaulted to not decrypting. If the new param should be
overloaded then I am curious why all the other params are using
defaults...??

I was following the pattern in place with the default params but I can
overload it if you prefer... I don't see it changing anything. I 
may be overlooking something..??

**Comment by leedavi** [comment]
I had the same logical thoughts.

But I did find that when you compile, when used with other assemblies that have not been compiled against the new version the compatiblity is broken.  (This might not be true with razor, because it compiles at runtime)

I therefore now try and leave the original method the same, and create a new method(s) with the extra params.  Sometimes  I even create multiple methods so we can keep compatiblity with assemblys that have not been update/recompiled.  I know this sounds a little crazy and defeats the idea of default values for params, but it's what I find happens.

**Comment by DNNMonster** [comment]
Because there are existing optional parameters in the method signature I cannot overload it unless I alter 
the method significantly because optional parameters must be the last parameters in the signature.  Pretty sure that approach won't work.  I could be wrong...

If you want to overload the function I believe we would have to rewrite it to drop all the optional params in favor of overloads.  It should not introduce breaking changes but it's more lines of code changing.  I can make that happen if you green light it.

Otherwise.. Send the func signatures you want to see and I'll implement...  Or make the mods if you have them in mind.  The rest of the code in the commit should not need changing.

**Comment by leedavi** [comment]
No, you just need to create a method for all possible params and call the major method from each method that has less params.  After all that's how we use to do it.   I don't think Microsoft have implemented optional params correctly…… or at least the compile should deal with it correctly, but it doesn't,

**Comment by DNNMonster** [comment]
Pretty sure you're describing overloading.  You'll have to push the bool parameter ahead of the strings with defaults.  This seems to start getting messy with overloads being used for all possible scenarios of optional params & trying not to introduce a breaking change with the ordering change in params.  Especially when the optional params are both the same type.  I still think the original commit is the way to go but I'm curious to see how you would achieve the same results.  If you spawn a branch I'll take a look at what you have in mind.  My gut says rewrite with no optional params(only overloads) or use the original commit.  It's a  grey zone on overloads vs optional params.  Mixing them is funky.  I'm not sure there is one right answer here but giving OS TextBox token encryption is the goal.

**Comment by DNNMonster** [comment]
I altered the approach to use a new overload but retain the original signature with no additional optional param.  The implementation migrated to the new signature with the encryption param.  I think that's the overload equivalent to the original commit.  Perhaps this is your pref..??

**Comment by leedavi** [comment]
Hi,

Sorry to be a pain with this.  It's not my preference, but I have seen it cause an issue in the past.  So now I avoid changing parms, if I can.

Thanks for the idea and the update.

**Pull request merged**
